//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsMoving
    {
        public int id { get; set; }
        public int idProduct { get; set; }
        public Nullable<decimal> CountStore { get; set; }
        public Nullable<decimal> CountShop { get; set; }
        public Nullable<decimal> Sold { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
